### ISSUE TITLE
Good practice...

### ISSUE THREAD

**Issue by BCFCODE** [BCFCODE/FocusToDo-Speed-Tracker#28]
![image](https://github.com/BCFCODE/FocusToDo-Speed-Tracker/assets/78473407/22773dfb-964f-4188-8b15-d7bb8727acf9)
با عنوان یک عادت خوب تمام این موارد رو در هر پول مشخص کن

_Originally posted by @BCFCODE in https://github.com/BCFCODE/FocusToDo-Speed-Tracker/issues/27#issuecomment-1798231084_

**Comment by majidbabakh** [comment]
کجا قرارش بدم؟

**Comment by BCFCODE** [comment]
> کجا قرارش بدم؟

این ایشو بسته شده...
