### ISSUE TITLE
Create a new branch and solve the problem with test

### ISSUE THREAD

**Issue by BCFCODE** [BCFCODE/FocusToDo-Speed-Tracker#32]
![image](https://github.com/BCFCODE/FocusToDo-Speed-Tracker/assets/78473407/8e7b2382-d12c-4aae-8665-824a2c9ee015)
بیا قشنگ بالا از اینجا که نوشته main از اینجا یه برنچ بزن
اسمشم بذار feature/time-measurement

الان ببین با این منشن واست نوتی میاد؟
@majidbabakh 
 ProTip! Notify someone on an issue with a mention, like: @majidbabakh .

جهت گرفتن اطلاعات بیشتر روی لینک کلیک کن
_Originally posted by @BCFCODE in https://github.com/BCFCODE/FocusToDo-Speed-Tracker/discussions/29#discussioncomment-7519895_

**Comment by majidbabakh** [comment]
اره اومد @BCFCODE
