### ISSUE TITLE
All of these tests must be passed

### ISSUE THREAD

**Issue by BCFCODE** [BCFCODE/FocusToDo-Speed-Tracker#53]
![image](https://github.com/BCFCODE/FocusToDo-Speed-Tracker/assets/78473407/2aee5ee2-8239-410d-9410-7b24b451564b)

تست های دیتا بیس آپدیت شد برنچ ها تو از اینجا بساز، دو تست دیتا بیس هم باید پاس بشه
باگ مربوط به تست hph برطرف شد ممنون بابت گزارش
@majidbabakh

_Originally posted by @BCFCODE in https://github.com/BCFCODE/FocusToDo-Speed-Tracker/discussions/52_

**Comment by majidbabakh** [comment]
تغییراتی که دادم اوکی نبود؟
@BCFCODE

**Comment by BCFCODE** [comment]
> تغییراتی که دادم اوکی نبود؟ @BCFCODE

همون طور که دو جای مختلف گفتم، اولین جا توی پول ریکوئستی که تایید اش کردی... یک برنچ بساز تمام کارهایی که کردی رو برای تمرین ادغام کن و پول ریکوئست بساز بفرست، من هنوز هیچ تغییری از سمت ات موفق نشدم ببینم

**Comment by BCFCODE** [comment]
> تغییراتی که دادم اوکی نبود؟ @BCFCODE

و اینکه چرا پول ریکوئست ها رو بستی؟! بذار اون شخصی که پول ریکوئست رو دریافت کرده اون رو ببنده یا برنچ رو دیلیت کنه، مگر اینکه بهت بگه و مشخص باشه الان وقتشه

**Comment by majidbabakh** [comment]
> > تغییراتی که دادم اوکی نبود؟ @BCFCODE
> 
> و اینکه چرا پول ریکوئست ها رو بستی؟! بذار اون شخصی که پول ریکوئست رو دریافت کرده اون رو ببنده یا برنچ رو دیلیت کنه، مگر اینکه بهت بگه و مشخص باشه الان وقتشه

طرف ممکنه pull request اشتباه فرستاده باشه منطقیه که پاکش کنه pull request درستو بفرسته !

**Comment by majidbabakh** [comment]
> > تغییراتی که دادم اوکی نبود؟ @BCFCODE
> 
> همون طور که دو جای مختلف گفتم، اولین جا توی پول ریکوئستی که تایید اش کردی... یک برنچ بساز تمام کارهایی که کردی رو برای تمرین ادغام کن و پول ریکوئست بساز بفرست، من هنوز هیچ تغییری از سمت ات موفق نشدم ببینم @majidbabakh

برو تو شاخه feature/currentHpd تغییرو ببین فقط تو اون تغییر دادم ببینی چطوریه تا تو اون یکی شاخه ام اعمالش کنم

**Comment by BCFCODE** [comment]
> > > تغییراتی که دادم اوکی نبود؟ @BCFCODE
> > 
> > و اینکه چرا پول ریکوئست ها رو بستی؟! بذار اون شخصی که پول ریکوئست رو دریافت کرده اون رو ببنده یا برنچ رو دیلیت کنه، مگر اینکه بهت بگه و مشخص باشه الان وقتشه
> 
> طرف ممکنه pull request اشتباه فرستاده باشه منطقیه که پاکش کنه pull request درستو بفرسته !

درسته من فک می کردم که می بایست یک توافق بر سرش باشه شاید اشتباه یاد گرفتم
متداول اش البته این هست:
دریافت کننده بعد از بررسی تصمیم بگیره
و اصولی تر اینه که یک برنچ دیگ بسازی تا وقتی ک تکلیف این پول ریکوئست مشخص بشه
البته هرجور خودت صلاح می دونی میتونی جلو بری و اجباری نیست

**Comment by BCFCODE** [comment]
> > > تغییراتی که دادم اوکی نبود؟ @BCFCODE
> > 
> > همون طور که دو جای مختلف گفتم، اولین جا توی پول ریکوئستی که تایید اش کردی... یک برنچ بساز تمام کارهایی که کردی رو برای تمرین ادغام کن و پول ریکوئست بساز بفرست، من هنوز هیچ تغییری از سمت ات موفق نشدم ببینم @majidbabakh
> 
> برو تو شاخه feature/currentHpd تغییرو ببین فقط تو اون تغییر دادم ببینی چطوریه تا تو اون یکی شاخه ام اعمالش کنم

معمولا پول ریکوئست ارسال میشه برو تو شاخه فلان نداشتیما، متوجه منظورت نیستم
پول ریکوئست ارسال کن، همه پول ریکوئست ها رو بستی!! تا تغییرات رو مرور کنم

**Comment by BCFCODE** [comment]
اگر می دونی این پروسه یکم ذهن تو بهم ریخته می تونیم ببندیم و ادامه ماجرا رو بریم، بهترین راه حل رو بهت دادم امیدوار بودم بپذیری...
بهترین کار ممکن ایجاد یک برنچ جدید هست الان، خودت لوکال تمام تغییرات رو مرج کنی توش، اون دو تا برنچ رو هم دیلیت کنی که ذهن ات مرتب بشه کامل، و بعد اون برنچ جدید رو پول ریکوئست بفرستی تا در بخش مربوطه به changes تفاوت ها رو با پاسخ صحیح که همون برنچ جدیدی هست که دیشب پول ریکوئست اش رو دادی مقایسه کنم و ادامه ماجرا

**Comment by majidbabakh** [comment]
> اگر می دونی این پروسه یکم ذهن تو بهم ریخته می تونیم ببندیم و ادامه ماجرا رو بریم، بهترین راه حل رو بهت دادم امیدوار بودم بپذیری... بهترین کار ممکن ایجاد یک برنچ جدید هست الان، خودت لوکال تمام تغییرات رو مرج کنی توش، اون دو تا برنچ رو هم دیلیت کنی که ذهن ات مرتب بشه کامل، و بعد اون برنچ جدید رو پول ریکوئست بفرستی تا در بخش مربوطه به changes تفاوت ها رو با پاسخ صحیح که همون برنچ جدیدی هست که دیشب پول ریکوئست اش رو فرستادم و تایید کردی مقایسه کنم و ادامه ماجرا @majidbabakh

نمیدونم هدف تمرین گیته یا انجام پروژه یا هردو
اگه تمرینه گیته که خب میشه سناریو خیلی راحت تر در نظر گرفت که تمرکز روی گیت باشه
اگه انجام پروژه ست که من یه تغییری توش دادم اصلا در نظر نگرفتی، اگه پروژه را کامل قبلا نوشتی همه چیش اوکیه پس من درگیرش نشم
اگه ام js نوشتی و UI ش مونده مشخص کن که UI چه شکلی باشه و داده ها کدوم قسمتا درگیر بشه تا UI شو بنویسم.

**Comment by BCFCODE** [comment]
اگر ضعف در گیت باشه هدف میشه رفع نقاط ضعف درگیت + انجام پروژه، اگر ضعف در گیت نباشه میشه انجام پروژه
پروژه چند تا ضرب و تقسیم بیشتر نیست از این ساده تر دیگه اسمش پروژه نیست، دمو هم نوشته بودم همونطور که دیدی، درحال ریفکتور هستیم
اجازه میدی بمن که تغییری که توی پروژه اعمال کردی رو ببینم؟
@majidbabakh

**Comment by BCFCODE** [comment]
> اگر ضعف در گیت باشه هدف میشه رفع نقاط ضعف درگیت + انجام پروژه، اگر ضعف در گیت نباشه میشه انجام پروژه پروژه چند تا ضرب و تقسیم بیشتر نیست از این ساده تر دیگه اسمش پروژه نیست، دمو هم نوشته بودم همونطور که دیدی، درحال ریفکتور هستیم اجازه میدی بمن که تغییری که توی پروژه اعمال کردی رو ببینم؟
اگر اضافه کردن یک برنچ و انجام تسک هایی که بهت دادم رو این ترجمه کردی که کل پروژه رو نوشتم، نه اینطور نیست، دیشب دیدم این خیلی طول کشید خودم نشستم نوشتم، فرستادم چک کنی، دیف بزنی رفع اشکال کنی روی برنچ هات اعمال کنی تا ادامه بدیم
 @majidbabakh

**Comment by BCFCODE** [comment]
یک هدف بیشتر وجود نداره، اونم استارت زدن وب سایت، تمام این هارو دارم وقت می ذارم انجام میدم که بتونی ریموت کار کنی، مفاهیم، قرارداد ها و... توی ذهن ات جا بیفته
لطفا توی ذهن ات همه چیز رو روشن کن، تنها چیزی که برای من روشن هست اینه که روزی یک ساعت تعهد تمرین گیت رو دادی، بدون هیچ حاشیه
@majidbabakh

**Comment by BCFCODE** [comment]
هر سوالی هم داری دارم جواب میدم
اگر چیز دیگه ای نیاز داری بگو، اگر نه قشنگ و محکم ادامه بده
@majidbabakh

**Comment by BCFCODE** [comment]
این رو 3 جای مختلف برات نوشتم: 
اگر می دونی این پروسه یکم ذهن تو بهم ریخته می تونیم ببندیم و ادامه ماجرا رو بریم، بهترین راه حل رو بهت دادم امیدوار بودم بپذیری...
بهترین کار ممکن ایجاد یک برنچ جدید هست الان، خودت لوکال تمام تغییرات رو مرج کنی توش، اون دو تا برنچ رو هم دیلیت کنی که ذهن ات مرتب بشه کامل، و بعد اون برنچ جدید رو پول ریکوئست بفرستی تا در بخش مربوطه به changes تفاوت ها رو با پاسخ صحیح که همون برنچ جدیدی هست که دیشب پول ریکوئست اش رو فرستادم و تایید کردی مقایسه کنم و ادامه ماجرا
در توان ات هست هر چی برنچ داری غیر از برنچ اصلی پاک کنی و این رو با عنوان یک تسک و تمرین انجام بدی؟
@majidbabakh

**Comment by majidbabakh** [comment]
مشکلی بابت ریموت کار کردن ندارم برا این مورد وقت نذار 
ضعف گیتم داره حل میشه  روزی نزدیک 2 ساعت دارم رو گیت کار میکنم
پروژه سخت نیست ولی هدفشم مشخص نیست اگه پروژه رو نوشتی برا گیت من داری وقت میذاری کنسلش کنیم بریم یه کار هدف مند تر

**Comment by majidbabakh** [comment]
من تغییراتو push کردم اگه موفق نشدی ببینی نمیدونم 
https://github.com/BCFCODE/FocusToDo-Speed-Tracker/blob/feature/currentHpd/app.js
