### ISSUE TITLE
Create new branch called feature/time/methods

### ISSUE THREAD

**Issue by BCFCODE** [BCFCODE/FocusToDo-Speed-Tracker#57]
بعد از اینکه مشکل دو برنچ حل شد یه برنج جدید بساز به اسم
feature/time/methods
و هردو شون رو توی این مرج کن
و بعد ارسال جهت بررسی
بذار اون برنچ ها جداگانه اول اوکی بشن
@majidbabakh

**Comment by BCFCODE** [comment]
برای اینکه تمرین کرده باشیش یه برنچ جدید بساز، این دو تا برنچ رو روش مرج کن، هر دوشو اونجا ادامه بده
هر جا هم گیر کردی برنچ ات رو با برنچ جدیدی که فرستادم و همه تستاش پاس شده diff کن فرقاشونو ببینی
نتیجه رو پول ریکوئست کن
تا بریم تسک بعدی
حتما روزی یک ساعت تعهد ات رو بذار، تقریبا پایه اولیه رو پیدا کردی فقط باید توی ذهنت جا بیفته که با کار کردن یواش یواش جا می افته

**Comment by BCFCODE** [comment]
> بعد از اینکه مشکل دو برنچ حل شد یه برنج جدید بساز به اسم feature/time/methods و هردو شون رو توی این مرج کن و بعد ارسال جهت بررسی بذار اون برنچ ها جداگانه اول اوکی بشن @majidbabakh

این رو صرفا جهت تمرین انجام بده و خیلی سریع، که از این بگذیرم و بریم مرحله بعد، چون برنچ جدیدی با تغییرات تصحیح شده که تایید اش هم کردی ایجاد شده 
@majidbabakh

**Comment by majidbabakh** [comment]
> > بعد از اینکه مشکل دو برنچ حل شد یه برنج جدید بساز به اسم feature/time/methods و هردو شون رو توی این مرج کن و بعد ارسال جهت بررسی بذار اون برنچ ها جداگانه اول اوکی بشن @majidbabakh
> 
> این رو صرفا جهت تمرین انجام بده و خیلی سریع، که از این بگذریم و بریم مرحله بعد، چون برنچ جدیدی با تغییرات تصحیح شده که تایید اش هم کردی ایجاد شده @majidbabakh

اینو دیگه ولش کن تغییراتو دیگه مرج کردیم 
بریم بعدی
@BCFCODE

**Comment by BCFCODE** [comment]
> > > بعد از اینکه مشکل دو برنچ حل شد یه برنج جدید بساز به اسم feature/time/methods و هردو شون رو توی این مرج کن و بعد ارسال جهت بررسی بذار اون برنچ ها جداگانه اول اوکی بشن @majidbabakh
> > 
> > 
> > این رو صرفا جهت تمرین انجام بده و خیلی سریع، که از این بگذریم و بریم مرحله بعد، چون برنچ جدیدی با تغییرات تصحیح شده که تایید اش هم کردی ایجاد شده @majidbabakh
> 
> اینو دیگه ولش کن تغییراتو دیگه مرج کردیم بریم بعدی @BCFCODE

قبل از این که ببندمش[ اینو روش انجام بده](https://github.com/BCFCODE/FocusToDo-Speed-Tracker/discussions/68) شات اش رو بفرس
@majidbabakh

**Comment by majidbabakh** [comment]
> > > > بعد از اینکه مشکل دو برنچ حل شد یه برنج جدید بساز به اسم feature/time/methods و هردو شون رو توی این مرج کن و بعد ارسال جهت بررسی بذار اون برنچ ها جداگانه اول اوکی بشن @majidbabakh
> > > 
> > > 
> > > این رو صرفا جهت تمرین انجام بده و خیلی سریع، که از این بگذریم و بریم مرحله بعد، چون برنچ جدیدی با تغییرات تصحیح شده که تایید اش هم کردی ایجاد شده @majidbabakh
> > 
> > 
> > اینو دیگه ولش کن تغییراتو دیگه مرج کردیم بریم بعدی @BCFCODE
> 
> قبل از این که ببندمش[ اینو روش انجام بده](https://github.com/BCFCODE/FocusToDo-Speed-Tracker/discussions/68) شات اش رو بفرس @majidbabakh

![image](https://github.com/BCFCODE/FocusToDo-Speed-Tracker/assets/36129754/24f830fd-7f0e-4bf8-9690-745483d288d6)

قبلش fetch کردم و سوئیچ کردم روش

**Comment by BCFCODE** [comment]
> > > > > بعد از اینکه مشکل دو برنچ حل شد یه برنج جدید بساز به اسم feature/time/methods و هردو شون رو توی این مرج کن و بعد ارسال جهت بررسی بذار اون برنچ ها جداگانه اول اوکی بشن @majidbabakh
> > > > 
> > > > 
> > > > این رو صرفا جهت تمرین انجام بده و خیلی سریع، که از این بگذریم و بریم مرحله بعد، چون برنچ جدیدی با تغییرات تصحیح شده که تایید اش هم کردی ایجاد شده @majidbabakh
> > > 
> > > 
> > > اینو دیگه ولش کن تغییراتو دیگه مرج کردیم بریم بعدی @BCFCODE
> > 
> > 
> > قبل از این که ببندمش[ اینو روش انجام بده](https://github.com/BCFCODE/FocusToDo-Speed-Tracker/discussions/68) شات اش رو بفرس @majidbabakh
> 
> ![image](https://user-images.githubusercontent.com/36129754/284019943-24f830fd-7f0e-4bf8-9690-745483d288d6.png)
> 
> قبلش fetch کردم و سوئیچ کردم روش

Done!
این کسیه که می خوام باهاش کار کنم!
@majidbabakh

**Comment by BCFCODE** [comment]
حالا قبل از اینکه این ایشو رو ببندم چون مشکل اش حل شده
پول ریکوئست رو این جا از ریموت حذف می کنم (که میشه از لوکال هم اینکارو کرد) و بعد برنچ رو هم حذف می کنم چون دیگه بدرد مون نمی خوره چون باگ فیکس شده با یه پول ریکوئست دیگه که فرستادی
کاری که می کنی، لاگی رو برای من بفرست که توش نه ریموت اش و نه لوکال اش نباشن، همینجا ریپلای کن
@majidbabakh

**Comment by majidbabakh** [comment]
> حالا قبل از اینکه این ایشو رو ببندم چون مشکل اش حل شده پول ریکوئست رو این جا از ریموت حذف می کنم (که میشه از لوکال هم اینکارو کرد) و بعد برنچ رو هم حذف می کنم چون دیگه بدرد مون نمی خوره چون باگ فیکس شده با یه پول ریکوئست دیگه که فرستادی کاری که می کنی، لاگی رو برای من بفرست که توش نه ریموت اش و نه لوکال اش نباشن، همینجا ریپلای کن @majidbabakh

![image](https://github.com/BCFCODE/FocusToDo-Speed-Tracker/assets/36129754/5cb152dc-6852-4e93-9e81-e7eae1ca0c23)
بفرما

**Comment by BCFCODE** [comment]
> > حالا قبل از اینکه این ایشو رو ببندم چون مشکل اش حل شده پول ریکوئست رو این جا از ریموت حذف می کنم (که میشه از لوکال هم اینکارو کرد) و بعد برنچ رو هم حذف می کنم چون دیگه بدرد مون نمی خوره چون باگ فیکس شده با یه پول ریکوئست دیگه که فرستادی کاری که می کنی، لاگی رو برای من بفرست که توش نه ریموت اش و نه لوکال اش نباشن، همینجا ریپلای کن @majidbabakh
> 
> ![image](https://user-images.githubusercontent.com/36129754/284021544-5cb152dc-6852-4e93-9e81-e7eae1ca0c23.png) بفرما

قرار نبود احساسات رو وارد کنیم چون قانونه ولی ایندفعه بصورت خودآگاه استثنا قایل میشم: عاشقتم @majidbabakh

**Comment by majidbabakh** [comment]
> > > حالا قبل از اینکه این ایشو رو ببندم چون مشکل اش حل شده پول ریکوئست رو این جا از ریموت حذف می کنم (که میشه از لوکال هم اینکارو کرد) و بعد برنچ رو هم حذف می کنم چون دیگه بدرد مون نمی خوره چون باگ فیکس شده با یه پول ریکوئست دیگه که فرستادی کاری که می کنی، لاگی رو برای من بفرست که توش نه ریموت اش و نه لوکال اش نباشن، همینجا ریپلای کن @majidbabakh
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/36129754/284021544-5cb152dc-6852-4e93-9e81-e7eae1ca0c23.png) بفرما
> 
> قرار نبود احساسات رو وارد کنیم چون قانونه ولی ایندفعه بصورت خودآگاه استثنا قایل میشم: عاشقتم @majidbabakh

گِی که نیسی ایشالا ؟🤣

**Comment by BCFCODE** [comment]
> > > > حالا قبل از اینکه این ایشو رو ببندم چون مشکل اش حل شده پول ریکوئست رو این جا از ریموت حذف می کنم (که میشه از لوکال هم اینکارو کرد) و بعد برنچ رو هم حذف می کنم چون دیگه بدرد مون نمی خوره چون باگ فیکس شده با یه پول ریکوئست دیگه که فرستادی کاری که می کنی، لاگی رو برای من بفرست که توش نه ریموت اش و نه لوکال اش نباشن، همینجا ریپلای کن @majidbabakh
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/36129754/284021544-5cb152dc-6852-4e93-9e81-e7eae1ca0c23.png) بفرما
> > 
> > 
> > قرار نبود احساسات رو وارد کنیم چون قانونه ولی ایندفعه بصورت خودآگاه استثنا قایل میشم: عاشقتم @majidbabakh
> 
> گِی که نیسی ایشالا ؟🤣

شرط عقل بر مراقبته :)
