### ISSUE TITLE
We have a problem with html rendering 

### ISSUE THREAD

**Issue by BCFCODE** [BCFCODE/FocusToDo-Speed-Tracker#62]

**Comment by BCFCODE** [comment]
Done!
این کسیه که لیاقت کار کردن در BCFCODE رو داره! @majidbabakh

**Comment by BCFCODE** [comment]
حالا یه لاگ بفرست که توش هیچ کدوم از این برنچ ها نباشه چون هر دوش رو از ریموت حذف کردم
البته میشه از لوکال هم حذف کرد
چون دیگه بدردمون نمی خوره
یادت باشه برنچ ها بوجود میاریم که بعد حذف شون کنیم، قرار نیست آشغال های هیستوریمون بشن
شات لاگ ات رو همینجا ریپلای کن
@majidbabakh

**Comment by majidbabakh** [comment]
> حالا یه لاگ بفرست که توش هیچ کدوم از این برنچ ها نباشه چون هر دوش رو از ریموت حذف کردم البته میشه از لوکال هم حذف کرد چون دیگه بدردمون نمی خوره یادت باشه برنچ ها بوجود میاریم که بعد حذف شون کنیم، قرار نیست آشغال های هیستوریمون بشن شات لاگ ات رو همینجا ریپلای کن @majidbabakh

اینا دو جا گفتی یا من اشتباه فرستادم؟

![image](https://github.com/BCFCODE/FocusToDo-Speed-Tracker/assets/36129754/bd2532ae-bcdb-4996-a97b-86a1624d4f7d)

**Comment by BCFCODE** [comment]
> > حالا یه لاگ بفرست که توش هیچ کدوم از این برنچ ها نباشه چون هر دوش رو از ریموت حذف کردم البته میشه از لوکال هم حذف کرد چون دیگه بدردمون نمی خوره یادت باشه برنچ ها بوجود میاریم که بعد حذف شون کنیم، قرار نیست آشغال های هیستوریمون بشن شات لاگ ات رو همینجا ریپلای کن @majidbabakh
> 
> اینا دو جا گفتی یا من اشتباه فرستادم؟
> 
> ![image](https://user-images.githubusercontent.com/36129754/284021889-bd2532ae-bcdb-4996-a97b-86a1624d4f7d.png)

درسته همینجا منتها لاگ ات رو تصویرشو کامل می خوام هیچی جز برنچ اصلی نباید توش باشه

**Comment by majidbabakh** [comment]
> > > حالا یه لاگ بفرست که توش هیچ کدوم از این برنچ ها نباشه چون هر دوش رو از ریموت حذف کردم البته میشه از لوکال هم حذف کرد چون دیگه بدردمون نمی خوره یادت باشه برنچ ها بوجود میاریم که بعد حذف شون کنیم، قرار نیست آشغال های هیستوریمون بشن شات لاگ ات رو همینجا ریپلای کن @majidbabakh
> > 
> > 
> > اینا دو جا گفتی یا من اشتباه فرستادم؟
> > ![image](https://user-images.githubusercontent.com/36129754/284021889-bd2532ae-bcdb-4996-a97b-86a1624d4f7d.png)
> 
> درسته همینجا منتها لاگ ات رو تصویرشو کامل می خوام هیچی جز برنچ اصلی نباید توش باشه

مگه وقتی برنچا را پاک کنی از لاگ پاک نمیشه؟
چیزی دیگه نیست جز برچ اصلی
![image](https://github.com/BCFCODE/FocusToDo-Speed-Tracker/assets/36129754/5afde519-8746-4048-8416-d8594d873870)

**Comment by BCFCODE** [comment]
> > > > حالا یه لاگ بفرست که توش هیچ کدوم از این برنچ ها نباشه چون هر دوش رو از ریموت حذف کردم البته میشه از لوکال هم حذف کرد چون دیگه بدردمون نمی خوره یادت باشه برنچ ها بوجود میاریم که بعد حذف شون کنیم، قرار نیست آشغال های هیستوریمون بشن شات لاگ ات رو همینجا ریپلای کن @majidbabakh
> > > 
> > > 
> > > اینا دو جا گفتی یا من اشتباه فرستادم؟
> > > ![image](https://user-images.githubusercontent.com/36129754/284021889-bd2532ae-bcdb-4996-a97b-86a1624d4f7d.png)
> > 
> > 
> > درسته همینجا منتها لاگ ات رو تصویرشو کامل می خوام هیچی جز برنچ اصلی نباید توش باشه
> 
> مگه وقتی برنچا را پاک کنی از لاگ پاک نمیشه؟ چیزی دیگه نیست جز برچ اصلی ![image](https://user-images.githubusercontent.com/36129754/284042188-5afde519-8746-4048-8416-d8594d873870.png)

ارتباط گیت لوکال با ریموت کلا قطعه، باید فرمان داد

**Comment by BCFCODE** [comment]
حله بنظر میرسه یه قدم هایی برداشتیم، منتظر تسک بعدی باش
این پول ریکوئست رو دیگه نیازی بهش نداریم می بندمش
اگر ایده ای داشتی منتظرم...
تمام مواردی که دیتا بیس می خواد رو باید براش آماده کنیم
الان که ساخت برنچ و ... رو اوکی شدی برای فرستادن ایده هات یا جلو جلو کار کردن و اعمال هر خلاقیتی می دونی چکار کنی...
@majidbabakh
