### ISSUE TITLE
feat: Implement Average Measurement Methods 📊

### ISSUE THREAD

**Issue by BCFCODE** [BCFCODE/FocusToDo-Speed-Tracker#71]
New task:
این برنچ رو از ریموت به لوکال انتقال بده و کار رو شروع کن

feature/majid-solution-avg-measurement

دو دیتای بعدیِ متد های میانگین...
من هم موازی باهات در حال حل کردن هستم، در یک برنچ دیگه
ددلاین: سه روز
تقریبا 3 تا 4 مسئله سطح هفت و هشت داخل اش هست که باید حل بشه
نکته : به
 Hint
 در کامنت نوشتم یه نگاه بنداز 

@majidbabakh

**Comment by majidbabakh** [comment]
قرار شد جزئیات پروژه را توضیح بدی

**Comment by BCFCODE** [comment]
> قرار شد جزئیات پروژه را توضیح بدی

جزییات خاصی که مد نظرت هست و ندونستش باعث میشه توانایی قدم از قدم بر نداشتن رو نداشته باشی، بصورت سوال جهت صرفه جویی در وقت مطرح کن، در غیر این صورت قبل از رسیدن به 1000 بعدی این پروژه باید بسته بشه، چالش پیش رو رو هم صرفا 5 تا مسئله در نظر بگیر که 3 روز برای حل کردن اش وقت هست اگر توانش رو داشتی انجامش بده
@majidbabakh

**Comment by majidbabakh** [comment]
پروژه چه قسمتایی داره (چه قسمتایی باید پیاده سازی بشه هر قسمتشو توضیح بده که چی هست)؟
در آخر چیا باید تو UI نمایش داده بشه؟ و UI به چه شکل باشه؟

**Comment by BCFCODE** [comment]
> پروژه چه قسمتایی داره (چه قسمتایی باید پیاده سازی بشه هر قسمتشو توضیح بده که چی هست)؟ در آخر چیا باید تو UI نمایش داده بشه؟ و UI به چه شکل باشه؟

ندونستن پاسخ هیچ کدوم از این دو سوال، توانایی قدم از قدم برداشتن رو ازت نمی گیره، اما بطور خلاصه: برای UI در حال برنامه ریزی هستم، احتمالا برای نمایش اطلاعات از نمودار استفاده کنیم، جزییات در آینده بصورت تسک ابلاغ خواهد شد
قسمت هایی که باید پیاده سازی بشه قدم به قدم مثل تسک جاری از طریق ایجاد ایشو (حرفه ای ترین حالت ممکن) ابلاغ میشه
اما در مورد سوال اصلی که پشت سوالات ات مخفی است، (اینکه قرار هست تا کجا توسعه پیدا کنه) مرزهایی رو مشخص کردم که بمحض نزدیک شدن بهش ابلاغ خواهم کرد
ایده آل هست که این ریپو با عنوان صفحه ای قابل لانچ و افزودن به وب سایت، ازش استفاده بشه چون مورد استقبال کاربران قرار گرفته
@majidbabakh

**Comment by majidbabakh** [comment]
امیدوارم در پروژه بعدی، اول پروژه تحلیل و طراحی بشه و روند اون از ابتدا مشخص شده باشه

**Comment by BCFCODE** [comment]
> امیدوارم در پروژه بعدی، اول پروژه تحلیل و طراحی بشه و روند اون از ابتدا مشخص شده باشه

من هم...
@majidbabakh

**Comment by majidbabakh** [comment]
> New task: این برنچ رو از ریموت به لوکال انتقال بده و کار رو شروع کن
> 
> feature/majid-solution-avg-measurement
> 
> دو دیتای بعدیِ متد های میانگین... من هم موازی باهات در حال حل کردن هستم، در یک برنچ دیگه ددلاین: سه روز تقریبا 3 تا 4 مسئله سطح هفت و هشت داخل اش هست که باید حل بشه نکته : به Hint در کامنت نوشتم یه نگاه بنداز
> 
> @majidbabakh

hint تو کامنت کجا نوشتی؟

**Comment by majidbabakh** [comment]
میانگین hpd یا hph نیست به چی باید گرفته بشه
مثلا hpd میانگین نسبت به تعداد روزای یک هفته گرفته بشه یا ماه؟
یا hph میانگین نسبت به ساعات یک روز؟
@BCFCODE

**Comment by BCFCODE** [comment]
> میانگین hpd یا hph نیست به چی باید گرفته بشه مثلا hpd میانگین نسبت به تعداد روزای یک هفته گرفته بشه یا ماه؟ یا hph میانگین نسبت به ساعات یک روز؟ @BCFCODE

میانگین نسبت به Hph و Hpd های قبل، مبنا روز ها نیستن، در واقع میانگین از محاسبه دوم امکان پذیره
@majidbabakh
