### ISSUE TITLE
Huge bug in currentHourPerHour and currentHourPerDay methods!

### ISSUE THREAD

**Issue by BCFCODE** [BCFCODE/FocusToDo-Speed-Tracker#72]
الگوریتم این دوتا متد رو یه بار با دقت چک کن ببین آیا باگ رو پیدا می کنی؟
آیا داره داده رو درست محاسبه می کنه؟
@majidbabakh

**Comment by majidbabakh** [comment]
چه ورودی بش دادی که متوجه باگ شدی؟

**Comment by BCFCODE** [comment]
> چه ورودی بش دادی که متوجه باگ شدی؟

دیشب بعد از بررسی الگوریتم اش متوجه شدم، اینکه آیا داره درست محاسبه می کنه یا نه... ورودی همون ورودی...
@majidbabakh

**Comment by BCFCODE** [comment]
> > چه ورودی بش دادی که متوجه باگ شدی؟
> 
> دیشب بعد از بررسی الگوریتم اش متوجه شدم، اینکه آیا داره درست محاسبه می کنه یا نه... ورودی همون ورودی... @majidbabakh

نکته: پیداش نکردم، صرفا به درستی محاسبه الگوریتم فعلی مشکوک شدم، این ایشو بهانه ای برای اطمینان از صحت الگوریتم جاری یا پیدا کردن باگ احتمالی است تا زمانی که بسته بشه

**Comment by majidbabakh** [comment]
> > > چه ورودی بش دادی که متوجه باگ شدی؟
> > 
> > 
> > دیشب بعد از بررسی الگوریتم اش متوجه شدم، اینکه آیا داره درست محاسبه می کنه یا نه... ورودی همون ورودی... @majidbabakh
> 
> نکته: هنوز پیداش نکردم، صرفا به درستی محاسبه الگوریتم فعلی مشکوک شدم، این ایشو بهانه ای برای اطمینان از صحت الگوریتم جاری یا پیدا کردن باگ احتمالی است تا زمانی که بسته بشه @majidbabakh

یعنی مطمئن نیسی که باگ داره یا نه؟

**Comment by BCFCODE** [comment]
> > > > چه ورودی بش دادی که متوجه باگ شدی؟
> > > 
> > > 
> > > دیشب بعد از بررسی الگوریتم اش متوجه شدم، اینکه آیا داره درست محاسبه می کنه یا نه... ورودی همون ورودی... @majidbabakh
> > 
> > 
> > نکته: هنوز پیداش نکردم، صرفا به درستی محاسبه الگوریتم فعلی مشکوک شدم، این ایشو بهانه ای برای اطمینان از صحت الگوریتم جاری یا پیدا کردن باگ احتمالی است تا زمانی که بسته بشه @majidbabakh
> 
> یعنی مطمئن نیسی که باگ داره یا نه؟

نه هنوز

**Comment by majidbabakh** [comment]
> > > > > چه ورودی بش دادی که متوجه باگ شدی؟
> > > > 
> > > > 
> > > > دیشب بعد از بررسی الگوریتم اش متوجه شدم، اینکه آیا داره درست محاسبه می کنه یا نه... ورودی همون ورودی... @majidbabakh
> > > 
> > > 
> > > نکته: هنوز پیداش نکردم، صرفا به درستی محاسبه الگوریتم فعلی مشکوک شدم، این ایشو بهانه ای برای اطمینان از صحت الگوریتم جاری یا پیدا کردن باگ احتمالی است تا زمانی که بسته بشه @majidbabakh
> > 
> > 
> > یعنی مطمئن نیسی که باگ داره یا نه؟
> 
> نه هنوز

😑

**Comment by BCFCODE** [comment]
> > > > > > چه ورودی بش دادی که متوجه باگ شدی؟
> > > > > 
> > > > > 
> > > > > دیشب بعد از بررسی الگوریتم اش متوجه شدم، اینکه آیا داره درست محاسبه می کنه یا نه... ورودی همون ورودی... @majidbabakh
> > > > 
> > > > 
> > > > نکته: هنوز پیداش نکردم، صرفا به درستی محاسبه الگوریتم فعلی مشکوک شدم، این ایشو بهانه ای برای اطمینان از صحت الگوریتم جاری یا پیدا کردن باگ احتمالی است تا زمانی که بسته بشه @majidbabakh
> > > 
> > > 
> > > یعنی مطمئن نیسی که باگ داره یا نه؟
> > 
> > 
> > نه هنوز
> 
> 😑

دقیق ترش اینه: هنوز فرصت بررسی دقیق پیدا نکردم واسه همین ایشو برای کمک گذاشتم

**Comment by majidbabakh** [comment]
قبلا چک کردم تو فرمولاش ظاهرا مشکلی ندیدم

این روش عیب یابی نیست به نظر من 
اگه از قسمت خاصیش خطایی دیدی باید مشخص بشه توی فلان قسمت چه ورودی دادی و چه خروجی داد که مورد انتظار نبوده تا بررسی بشه چرا درست کار نکرده

ولی اگه در حالت کلی میخوای برنامه را تست کنی یه تست براش بنویس دیگه دوره دستی تست کردن گذشت
اگه توی تست اتوماتیک خطایی ندیدی پس احتمالا خطایی نداره دیگه تو زمان ریلیز کردنش و تست واقعی باید دید چطوری عمل میکنه

**Comment by BCFCODE** [comment]
> قبلا چک کردم تو فرمولاش ظاهرا مشکلی ندیدم
> 
> این روش عیب یابی نیست به نظر من اگه از قسمت خاصیش خطایی دیدی باید مشخص بشه توی فلان قسمت چه ورودی دادی و چه خروجی داد که مورد انتظار نبوده تا بررسی بشه چرا درست کار نکرده
> 
> ولی اگه در حالت کلی میخوای برنامه را تست کنی یه تست براش بنویس دیگه دوره دستی تست کردن گذشت اگه توی تست اتوماتیک خطایی ندیدی پس احتمالا خطایی نداره دیگه تو زمان ریلیز کردنش و تست واقعی باید دید چطوری عمل میکنه

ظاهرا مشکلی ندیدم که نداریم خلاصه اش بگو خودت انجامش بده، انجامش میدم
در مورد تست هم باید بگم این مورد باید بررسی الگوریتم بشه، که این کار رو تست اتوماتیک انجام نمیده، تست اتوماتیک و هم دست بقول تو دستی در تمام دوره ها وجود خواهد داشت در کنار هم...
ولی خب مرسی که وقت گذاشتی نوشتی کامل ...

**Comment by BCFCODE** [comment]
> > > قبلا چک کردم تو فرمولاش ظاهرا مشکلی ندیدم
> > > این روش عیب یابی نیست به نظر من اگه از قسمت خاصیش خطایی دیدی باید مشخص بشه توی فلان قسمت چه ورودی دادی و چه خروجی داد که مورد انتظار نبوده تا بررسی بشه چرا درست کار نکرده
> > > ولی اگه در حالت کلی میخوای برنامه را تست کنی یه تست براش بنویس دیگه دوره دستی تست کردن گذشت اگه توی تست اتوماتیک خطایی ندیدی پس احتمالا خطایی نداره دیگه تو زمان ریلیز کردنش و تست واقعی باید دید چطوری عمل میکنه
> > 
> > 
> > ظاهرا مشکلی ندیدم که نداریم خلاصه اش بگو خودت انجامش بده، انجامش میدم در مورد تست هم باید بگم این مورد باید بررسی الگوریتم بشه، که این کار رو تست اتوماتیک انجام نمیده، تست اتوماتیک و هم دست بقول تو دستی در تمام دوره ها وجود خواهد داشت در کنار هم... ولی خب مرسی که وقت گذاشتی نوشتی کامل ...
> 
> منظور بررسی الگوریتمیش بود ولی خودت انجامش بده بیشتر در موردش میدی و راجبش فکر کردی خواهش میکنم

جوابی که به تست اتوماتیک میدی داره صحیح نشون میده، اینجاست که باید بقول تو دستی انجامش بدی ببینی اصلا اون الگوریتم داره به جواب صحیح میرسه یا نه، و بعد تست اتوماتیک ات رو برای مراجعات بعدی بنا اصلاح کنی، موضوع اینه و منظور تو رو هم متوجه میشم... اونم منی که بواس یه جمع و منها هم تست می نویسم....
